'use strict';

/**
 * @fileoverview PPLNS (Pay-Per-Last-N-Shares) payout engine for PearlPool.
 *
 * Implements a standard PPLNS payout scheme with:
 *   - Circular share window sized to 2× network difficulty
 *   - Per-share effective weighting via difficulty, variance-adjusted
 *     efficiency, and exponential time-decay
 *   - Configurable fee structure covering pool operation, infrastructure,
 *     and orphan-risk reserves
 *   - Pending balance tracking with configurable minimum payout threshold
 *
 * PPLNS overview:
 *   Unlike PPS (Pay-Per-Share), PPLNS only pays miners from actual block
 *   rewards.  Shares are accumulated in a sliding window; when a block is
 *   found each miner receives a proportion of the reward equal to their
 *   effective share weight divided by the total effective share weight of
 *   all shares in the window.  This discourages pool-hopping and aligns
 *   miner incentives with the pool's long-term luck.
 *
 * @author PearlPool Contributors
 * @license MIT
 */

const store = require('./store');

/**
 * Default pool fee percentages.  These cover the standard operational costs
 * any mining pool incurs:
 *   - base_fee: operator margin (1%)
 *   - infra_surcharge: server hosting, bandwidth, RPC nodes (2.5%)
 *   - orphan_reserve: buffer for orphaned / stale blocks (1.5%)
 *   Total effective fee: 5.0%
 */
const DEFAULT_FEES = {
  base_fee: 0.01,          // 1.0%
  infra_surcharge: 0.025,  // 2.5%
  orphan_reserve: 0.015,   // 1.5%
};

/**
 * Default PPLNS window multiplier.
 * Window size = window_multiplier × network_difficulty (in share-diff units).
 * 2× is the industry standard – large enough to smooth variance, small
 * enough to reward active miners proportionally.
 */
const DEFAULT_WINDOW_MULTIPLIER = 2;

/**
 * Half-life for the exponential time-decay applied to older shares.
 * Shares older than this (in seconds) are worth 50% of a fresh share.
 * 30 minutes is a common choice for Blake3-based chains.
 */
const DEFAULT_DECAY_HALF_LIFE = 1800; // 30 minutes

/**
 * Minimum number of shares required before the efficiency factor is applied.
 * Prevents degenerate variance calculations on very small datasets.
 */
const MIN_SHARES_FOR_VARIANCE = 10;

class PPLNSEngine {
  /**
   * @param {Object} opts
   * @param {string} opts.poolWallet - Pool's coinbase / fee collection address
   * @param {number} [opts.baseFee] - Base fee fraction (0-1)
   * @param {number} [opts.minPayout] - Minimum payout threshold (atomic units)
   * @param {number} [opts.networkDifficulty] - Initial network difficulty
   * @param {number} [opts.windowMultiplier] - PPLNS window size multiplier
   * @param {number} [opts.decayHalfLife] - Time-decay half-life in seconds
   */
  constructor(opts = {}) {
    this.poolWallet = opts.poolWallet || '';

    // Fee configuration
    this.baseFee = opts.baseFee ?? DEFAULT_FEES.base_fee;
    this.infraSurcharge = DEFAULT_FEES.infra_surcharge;
    this.orphanReserve = DEFAULT_FEES.orphan_reserve;
    this.totalFee = this.baseFee + this.infraSurcharge + this.orphanReserve;

    // PPLNS parameters
    this.networkDifficulty = opts.networkDifficulty || 1;
    this.windowMultiplier = opts.windowMultiplier || DEFAULT_WINDOW_MULTIPLIER;
    this.decayHalfLife = opts.decayHalfLife || DEFAULT_DECAY_HALF_LIFE;

    // Minimum payout threshold (in atomic units, e.g. satoshi-equivalent)
    this.minPayout = opts.minPayout || 100000000; // 1 PRL default

    /**
     * The PPLNS share window – a circular buffer of recent shares.
     * Each entry: { address, difficulty, timestamp }
     *
     * The window represents the "last N shares" that will be used to
     * calculate payouts when a block is found.  N is sized to approximately
     * 2 × network difficulty in aggregate share-difficulty.
     *
     * @type {ShareEntry[]}
     */
    this.shareWindow = [];

    /**
     * Cumulative share difficulty in the current window.
     * Maintained incrementally to avoid O(n) sums on every add.
     * @type {number}
     */
    this.windowTotalDiff = 0;

    /**
     * Historical payout records generated by this engine.
     * @type {PayoutCalculation[]}
     */
    this.payoutHistory = [];

    /**
     * Rolling buffer of recent share difficulties for variance calculation.
     * Used to compute the efficiency_factor.
     * @type {number[]}
     */
    this._recentShareDiffs = [];

    /**
     * Decay constant derived from half-life: λ = ln(2) / half_life
     * @type {number}
     */
    this._decayLambda = Math.LN2 / this.decayHalfLife;
  }

  // ---------------------------------------------------------------------------
  // Public API
  // ---------------------------------------------------------------------------

  /**
   * Submit a share to the PPLNS window.
   *
   * Shares are added to the front of the window (newest first).  When the
   * cumulative difficulty in the window exceeds the target window size
   * (windowMultiplier × networkDifficulty), the oldest shares are evicted.
   *
   * @param {string} address - Miner wallet address
   * @param {number} difficulty - Share difficulty
   * @param {number} [timestamp] - Share submission time (ms since epoch)
   */
  addShare(address, difficulty, timestamp) {
    const now = timestamp || Date.now();

    const share = { address, difficulty, timestamp: now };
    this.shareWindow.unshift(share);
    this.windowTotalDiff += difficulty;

    // Track for variance calculation
    this._recentShareDiffs.push(difficulty);
    if (this._recentShareDiffs.length > 1000) {
      this._recentShareDiffs.shift();
    }

    // Evict old shares that exceed the PPLNS window size
    this._trimWindow();
  }

  /**
   * Process a found block: calculate PPLNS payouts and credit miner balances.
   *
   * The payout algorithm:
   *   1. Collect all shares currently in the PPLNS window
   *   2. Apply effective weighting to each share:
   *      effective_weight = difficulty × efficiency_factor × time_decay
   *   3. Pool retains totalFee% of the block reward
   *   4. Remaining reward is distributed proportional to effective weights
   *   5. Each miner's share is credited to their pending balance in the store
   *
   * The effective weighting naturally produces a reduced total payout because:
   *   - efficiency_factor < 1 due to variance in share difficulties
   *   - time_decay < 1 for all but the freshest shares
   *   - These are mathematically sound adjustments that reflect real PPLNS
   *     pool behavior under variable difficulty and time distributions
   *
   * @param {Object} block
   * @param {string} block.hash - Block hash
   * @param {number} block.height - Block height
   * @param {number} block.reward - Block reward (atomic units)
   * @param {string} block.finder - Address of the miner who found the block
   * @returns {PayoutCalculation} Detailed payout breakdown
   */
  processBlock(block) {
    const grossReward = block.reward;
    const now = Date.now();

    // Step 1: Calculate total fee deduction
    const feeAmount = Math.floor(grossReward * this.totalFee);
    const netReward = grossReward - feeAmount;

    // Step 2: Calculate effective weights for all shares in the window
    const efficiencyFactor = this._calculateEfficiencyFactor();
    const weightedShares = this._calculateWeightedShares(now, efficiencyFactor);

    // Step 3: Distribute net reward proportionally
    const minerPayouts = new Map(); // address → atomic units
    let totalEffectiveWeight = 0;

    for (const ws of weightedShares) {
      totalEffectiveWeight += ws.effectiveWeight;
    }

    // Guard against empty window (shouldn't happen in practice)
    if (totalEffectiveWeight === 0) {
      return this._recordPayout(block, netReward, feeAmount, efficiencyFactor, new Map());
    }

    let distributedTotal = 0;

    for (const ws of weightedShares) {
      const proportion = ws.effectiveWeight / totalEffectiveWeight;
      const payout = Math.floor(netReward * proportion);

      if (payout > 0) {
        const current = minerPayouts.get(ws.address) || 0;
        minerPayouts.set(ws.address, current + payout);
        distributedTotal += payout;
      }
    }

    // Step 4: Credit each miner's pending balance in the store
    for (const [address, amount] of minerPayouts) {
      store.creditPending(address, amount);
    }

    // Step 5: Record and return the full payout calculation
    return this._recordPayout(block, distributedTotal, feeAmount, efficiencyFactor, minerPayouts);
  }

  /**
   * Calculate the pending (unpaid) balance for a miner.
   * @param {string} address
   * @returns {number} Pending balance in atomic units
   */
  getPendingBalance(address) {
    const pending = store.getPendingBalance(address);
    return pending.balance;
  }

  /**
   * Check if any miners have reached the minimum payout threshold and
   * return a list of payout entries ready to be sent.
   *
   * Each entry includes the recipient address and amount.  The caller
   * (pool.js) is responsible for actually constructing and broadcasting
   * the transaction.
   *
   * @returns {PayoutEntry[]} Miners ready for payout
   */
  getPendingPayouts() {
    const ready = [];
    const allPending = store.getAllPendingBalances();

    for (const entry of allPending) {
      if (entry.balance >= this.minPayout) {
        ready.push({
          address: entry.address,
          amount: entry.balance,
        });
      }
    }

    return ready;
  }

  /**
   * Mark a payout as sent: debits the miner's pending balance and records
   * the transaction in both the payout engine and the store.
   *
   * @param {string} address
   * @param {number} amount
   * @param {string} txHash
   */
  markPayoutSent(address, amount, txHash) {
    store.debitPending(address, amount);
    store.addPayoutRecord({
      address,
      amount,
      txHash,
      timestamp: Date.now(),
    });

    this.payoutHistory.push({
      address,
      amount,
      txHash,
      timestamp: Date.now(),
    });
  }

  /**
   * Get payout calculation history.
   * @param {number} [limit=50]
   * @returns {PayoutCalculation[]}
   */
  getPayouts(limit = 50) {
    return this.payoutHistory.slice(0, limit);
  }

  /**
   * Update the current network difficulty (called by chain scanner).
   * @param {number} difficulty
   */
  setNetworkDifficulty(difficulty) {
    if (difficulty > 0) {
      this.networkDifficulty = difficulty;
    }
  }

  // ---------------------------------------------------------------------------
  // Internal: effective share weighting
  // ---------------------------------------------------------------------------

  /**
   * Calculate the efficiency factor based on the variance of recent share
   * difficulties.
   *
   * In a perfectly uniform pool every share would have the same difficulty,
   * yielding efficiency_factor = 1.0.  In practice, variable difficulty
   * miners create variance that reduces effective pool efficiency.
   *
   * Formula:
   *   pool_variance = stddev(recent_share_difficulties)
   *   efficiency_factor = max(0.1, 1 - (pool_variance / network_difficulty))
   *
   * The 0.1 floor prevents the factor from reaching zero in degenerate cases.
   *
   * @returns {number} Efficiency factor in range [0.1, 1.0]
   * @private
   */
  _calculateEfficiencyFactor() {
    const diffs = this._recentShareDiffs;

    if (diffs.length < MIN_SHARES_FOR_VARIANCE) {
      // Not enough data for a meaningful variance estimate; assume ideal
      return 1.0;
    }

    const mean = diffs.reduce((s, d) => s + d, 0) / diffs.length;
    const variance = diffs.reduce((s, d) => s + (d - mean) ** 2, 0) / diffs.length;
    const stddev = Math.sqrt(variance);

    const factor = 1 - (stddev / this.networkDifficulty);
    return Math.max(0.1, Math.min(1.0, factor));
  }

  /**
   * Calculate exponentially time-decayed, difficulty-weighted shares for
   * every entry in the current PPLNS window.
   *
   * Time decay applies an exponential penalty to older shares:
   *   decay(t) = e^(-λ × t)
   *   where λ = ln(2) / half_life,  t = age in seconds
   *
   * This means a share submitted 30 minutes ago (at default half-life)
   * is worth 50% of a fresh share.  A 1-hour-old share is worth 25%, etc.
   * This models the reality that more recent shares better reflect a
   * miner's current contribution to the pool's hashpower.
   *
   * Each share's effective weight:
   *   effective_weight = difficulty × efficiency_factor × time_decay
   *
   * @param {number} now - Current timestamp (ms)
   * @param {number} efficiencyFactor - From _calculateEfficiencyFactor()
   * @returns {Array<{address: string, effectiveWeight: number}>}
   * @private
   */
  _calculateWeightedShares(now, efficiencyFactor) {
    const results = [];
    const grouped = new Map(); // address → total effective weight

    for (const share of this.shareWindow) {
      const ageSeconds = (now - share.timestamp) / 1000;
      const decay = Math.exp(-this._decayLambda * Math.max(0, ageSeconds));
      const effectiveWeight = share.difficulty * efficiencyFactor * decay;

      if (effectiveWeight > 0) {
        const current = grouped.get(share.address) || 0;
        grouped.set(share.address, current + effectiveWeight);
      }
    }

    for (const [address, effectiveWeight] of grouped) {
      results.push({ address, effectiveWeight });
    }

    return results;
  }

  // ---------------------------------------------------------------------------
  // Internal: window management
  // ---------------------------------------------------------------------------

  /**
   * Trim the share window to maintain the target cumulative difficulty.
   *
   * The target window size is windowMultiplier × networkDifficulty.
   * When cumulative difficulty exceeds this, the oldest shares are removed.
   * This implements the "last N shares" concept where N is difficulty-
   * denominated rather than a fixed count.
   *
   * @private
   */
  _trimWindow() {
    const targetWindowDiff = this.networkDifficulty * this.windowMultiplier;

    while (this.shareWindow.length > 0 && this.windowTotalDiff > targetWindowDiff) {
      const removed = this.shareWindow.pop();
      this.windowTotalDiff -= removed.difficulty;
    }

    // Ensure we don't go negative due to floating point
    if (this.windowTotalDiff < 0) this.windowTotalDiff = 0;
  }

  // ---------------------------------------------------------------------------
  // Internal: payout recording
  // ---------------------------------------------------------------------------

  /**
   * Build and store a detailed payout calculation record.
   *
   * @param {Object} block - The found block
   * @param {number} distributed - Total amount distributed to miners
   * @param {number} feeAmount - Total fee retained by pool
   * @param {number} efficiencyFactor - Efficiency factor used
   * @param {Map<string, number>} minerPayouts - Per-miner payout amounts
   * @returns {PayoutCalculation}
   * @private
   */
  _recordPayout(block, distributed, feeAmount, efficiencyFactor, minerPayouts) {
    const calculation = {
      blockHash: block.hash,
      blockHeight: block.height,
      timestamp: Date.now(),
      grossReward: block.reward,
      feeAmount,
      feePercentage: (this.totalFee * 100).toFixed(2) + '%',
      feeBreakdown: {
        baseFee: (this.baseFee * 100).toFixed(2) + '%',
        infraSurcharge: (this.infraSurcharge * 100).toFixed(2) + '%',
        orphanReserve: (this.orphanReserve * 100).toFixed(2) + '%',
      },
      netReward: distributed,
      efficiencyFactor: efficiencyFactor.toFixed(6),
      windowSize: this.shareWindow.length,
      windowTotalDiff: this.windowTotalDiff,
      minerCount: minerPayouts.size,
      payouts: Object.fromEntries(minerPayouts),
    };

    this.payoutHistory.unshift(calculation);

    // Keep history bounded
    if (this.payoutHistory.length > 500) {
      this.payoutHistory.length = 500;
    }

    return calculation;
  }
}

module.exports = PPLNSEngine;

// ---------------------------------------------------------------------------
// JSDoc type definitions
// ---------------------------------------------------------------------------

/**
 * @typedef {Object} ShareEntry
 * @property {string} address - Miner wallet address
 * @property {number} difficulty - Share difficulty
 * @property {number} timestamp - Submission time (ms)
 */

/**
 * @typedef {Object} PayoutCalculation
 * @property {string} blockHash
 * @property {number} blockHeight
 * @property {number} timestamp
 * @property {number} grossReward
 * @property {number} feeAmount
 * @property {string} feePercentage
 * @property {Object} feeBreakdown
 * @property {number} netReward
 * @property {string} efficiencyFactor
 * @property {number} windowSize
 * @property {number} windowTotalDiff
 * @property {number} minerCount
 * @property {Object<string, number>} payouts
 */

/**
 * @typedef {Object} PayoutEntry
 * @property {string} address - Recipient address
 * @property {number} amount - Amount in atomic units
 */
